spring.datasource: # Database information
  url: "jdbc:mysql://localhost:3306/hrmdata?useSSL=false"
  username: "user"
  password: "1234"
  testWhileIdle: true
  validationQuery: "SELECT 1"

spring.jpa: # JPA configuration
  hibernate.ddl-auto: "update"
  show-sql: false
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

demo.security.jwt: # Customized JWT token properties
  tokenExpirationTime: 1 # Number of minutes
  refreshTokenExpTime: 30 # Minutes
  tokenIssuer: "http://www.authright.com"
  tokenSigningKey: "xm8EV6Hy5RMFK4EEACIDAwQus"